//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accesorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accesorio()
        {
            this.accesorio_grupo = new HashSet<accesorio_grupo>();
            this.detalle_accesorio = new HashSet<detalle_accesorio>();
        }
    
        public int id { get; set; }
        public Nullable<int> tipo_accesorio_id { get; set; }
        public Nullable<int> material_id { get; set; }
    
        public virtual material material { get; set; }
        public virtual tipo_accesorio tipo_accesorio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accesorio_grupo> accesorio_grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_accesorio> detalle_accesorio { get; set; }
    }
}
