//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_assignment
    {
        public string item_name { get; set; }
        public string user_id { get; set; }
        public Nullable<int> created_at { get; set; }
    
        public virtual auth_item auth_item { get; set; }
    }
}
