//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public auth_item()
        {
            this.auth_assignment = new HashSet<auth_assignment>();
            this.auth_item_child = new HashSet<auth_item_child>();
        }
    
        public string name { get; set; }
        public int type { get; set; }
        public string description { get; set; }
        public string rule_name { get; set; }
        public string data { get; set; }
        public Nullable<int> created_at { get; set; }
        public Nullable<int> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auth_assignment> auth_assignment { get; set; }
        public virtual auth_rule auth_rule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<auth_item_child> auth_item_child { get; set; }
    }
}
