//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_accesorio
    {
        public int id { get; set; }
        public Nullable<int> accesorio_id { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<int> caracteristica_accesorio_id { get; set; }
        public Nullable<decimal> medida { get; set; }
        public Nullable<int> unidad_id { get; set; }
        public string tipo { get; set; }
    
        public virtual accesorio accesorio { get; set; }
        public virtual caracteristica_accesorio caracteristica_accesorio { get; set; }
        public virtual unidad unidad { get; set; }
    }
}
