//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de GaillardModel.edmx.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CasaGaillard.Models
{
    using System;

    public partial class Equipo
    {
        public int Id { get; set; }
        public int InstalacionId { get; set; }
        public Nullable<int> EquipoPadreId { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Fabricante { get; set; }
        public string Modelo { get; set; }
        public string NumeroSerie { get; set; }
        public Nullable<decimal> Potencia { get; set; }
        public Nullable<decimal> Caudal { get; set; }
        public Nullable<decimal> Presion { get; set; }
        public Nullable<decimal> Voltaje { get; set; }
        public Nullable<System.DateTime> FechaInstalacion { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public bool Activo { get; set; }
        public string Observaciones { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}
