//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de GaillardModel.edmx.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CasaGaillard.Models
{
    using System;

    public partial class EquipoAccesorio
    {
        public int Id { get; set; }
        public int EquipoId { get; set; }
        public int AccesorioId { get; set; }
        public int Cantidad { get; set; }
        public string Posicion { get; set; }
        public string NumeroSerie { get; set; }
        public Nullable<System.DateTime> FechaInstalacion { get; set; }
        public Nullable<System.DateTime> FechaRetirada { get; set; }
        public bool Activo { get; set; }
        public string Observaciones { get; set; }
    }
}
