//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GaillardEntities : DbContext
    {
        public GaillardEntities()
            : base("name=GaillardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accesorio> Accesorios { get; set; }
        public virtual DbSet<AccesorioGrupo> AccesorioGrupoes { get; set; }
        public virtual DbSet<CaracteristicaAccesorio> CaracteristicaAccesorios { get; set; }
        public virtual DbSet<Compartimento> Compartimentoes { get; set; }
        public virtual DbSet<Cuba> Cubas { get; set; }
        public virtual DbSet<DetalleAccesorio> DetalleAccesorios { get; set; }
        public virtual DbSet<Grupo> Grupoes { get; set; }
        public virtual DbSet<MantenimientoVehiculo> MantenimientoVehiculoes { get; set; }
        public virtual DbSet<Material> Materials { get; set; }
        public virtual DbSet<Operacion> Operacions { get; set; }
        public virtual DbSet<Operario> Operarios { get; set; }
        public virtual DbSet<Plataforma> Plataformas { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Revision> Revisions { get; set; }
        public virtual DbSet<RevisionVehiculo> RevisionVehiculoes { get; set; }
        public virtual DbSet<Situacion> Situacions { get; set; }
        public virtual DbSet<TipoAccesorio> TipoAccesorios { get; set; }
        public virtual DbSet<TipoGrupo> TipoGrupoes { get; set; }
        public virtual DbSet<TipoMantenimiento> TipoMantenimientoes { get; set; }
        public virtual DbSet<TipoOperacion> TipoOperacions { get; set; }
        public virtual DbSet<TipoRevision> TipoRevisions { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculoes { get; set; }
        public virtual DbSet<Unidad> Unidads { get; set; }
        public virtual DbSet<Vehiculo> Vehiculoes { get; set; }
    }
}
