//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GaillardEntities : DbContext
    {
        public GaillardEntities()
            : base("name=GaillardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accesorio> accesorios { get; set; }
        public virtual DbSet<accesorio_grupo> accesorio_grupo { get; set; }
        public virtual DbSet<auth_assignment> auth_assignment { get; set; }
        public virtual DbSet<auth_item> auth_item { get; set; }
        public virtual DbSet<auth_item_child> auth_item_child { get; set; }
        public virtual DbSet<auth_rule> auth_rule { get; set; }
        public virtual DbSet<caracteristica_accesorio> caracteristica_accesorio { get; set; }
        public virtual DbSet<compartimento> compartimentoes { get; set; }
        public virtual DbSet<cuba> cubas { get; set; }
        public virtual DbSet<detalle_accesorio> detalle_accesorio { get; set; }
        public virtual DbSet<grupo> grupoes { get; set; }
        public virtual DbSet<mantenimiento_vehiculo> mantenimiento_vehiculo { get; set; }
        public virtual DbSet<material> materials { get; set; }
        public virtual DbSet<migration> migrations { get; set; }
        public virtual DbSet<oper> opers { get; set; }
        public virtual DbSet<operacion> operacions { get; set; }
        public virtual DbSet<operario> operarios { get; set; }
        public virtual DbSet<plataforma> plataformas { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<revision> revisions { get; set; }
        public virtual DbSet<revision_vehiculo> revision_vehiculo { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<rol_oper> rol_oper { get; set; }
        public virtual DbSet<situacion> situacions { get; set; }
        public virtual DbSet<tipo_accesorio> tipo_accesorio { get; set; }
        public virtual DbSet<tipo_grupo> tipo_grupo { get; set; }
        public virtual DbSet<tipo_mantenimiento> tipo_mantenimiento { get; set; }
        public virtual DbSet<tipo_operacion> tipo_operacion { get; set; }
        public virtual DbSet<tipo_revision> tipo_revision { get; set; }
        public virtual DbSet<tipo_vehiculo> tipo_vehiculo { get; set; }
        public virtual DbSet<unidad> unidads { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vehiculo> vehiculoes { get; set; }
    }
}
