//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.AccesoriosGrupo = new HashSet<AccesorioGrupo>();
        }
    
        public int ID { get; set; }
        public int TipoGrupoID { get; set; }
        public int CubaID { get; set; }
        public int CompartimentoID { get; set; }
        public int SituacionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccesorioGrupo> AccesoriosGrupo { get; set; }
        public virtual TipoGrupo TipoGrupo { get; set; }
        public virtual Cuba Cuba { get; set; }
        public virtual Situacion Situacion { get; set; }
        public virtual Compartimento Compartimento { get; set; }
    }
}
