//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de GaillardModel.edmx.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CasaGaillard.Models
{
    using System;

    public partial class InstalacionDocumento
    {
        public int Id { get; set; }
        public int InstalacionId { get; set; }
        public string Nombre { get; set; }
        public string RutaArchivo { get; set; }
        public string TipoDocumento { get; set; }
        public string CodigoPlano { get; set; }
        public Nullable<System.DateTime> FechaDocumento { get; set; }
        public DateTime FechaAlta { get; set; }
    }
}
