//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de GaillardModel.edmx.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CasaGaillard.Models
{
    using System;

    public partial class Instalacion
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> TipoInstalacionId { get; set; }
        public Nullable<int> UbicacionId { get; set; }
        public Nullable<int> ResponsablePersonaId { get; set; }
        public Nullable<System.DateTime> FechaPuestaMarcha { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public byte Criticidad { get; set; }
        public string Estado { get; set; }
        public string CodigoPlano { get; set; }
        public bool CriticaProduccion { get; set; }
        public bool CriticaSeguridad { get; set; }
        public string Observaciones { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
