//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoVehiculo
    {
        public int ID { get; set; }
        public Nullable<int> VehiculoID { get; set; }
        public Nullable<System.DateTime> FechaMantenimiento { get; set; }
        public Nullable<int> TipoMantenimientoID { get; set; }
        public string DetalleMantenimiento { get; set; }
        public Nullable<int> OperarioID { get; set; }
        public Nullable<int> Kilometros { get; set; }
    }
}
