//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantenimiento_vehiculo
    {
        public int id { get; set; }
        public Nullable<int> id_vehiculo { get; set; }
        public Nullable<System.DateTime> fecha_mantenimiento { get; set; }
        public Nullable<int> id_tipo_mantenimiento { get; set; }
        public string detalle_mantenimiento { get; set; }
        public Nullable<int> id_operario { get; set; }
        public Nullable<int> kilometros { get; set; }
    
        public virtual operario operario { get; set; }
        public virtual tipo_mantenimiento tipo_mantenimiento { get; set; }
        public virtual vehiculo vehiculo { get; set; }
    }
}
