//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Material
    {
        public Material()
        {
            this.Accesorios = new HashSet<Accesorio>();
            this.Cubas = new HashSet<Cuba>();
            this.Compartimentos = new HashSet<Compartimento>();
        }
    
        public int ID { get; set; }

        [Display(Name = "Material")]
        public string Material1 { get; set; }

        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
    
        public virtual ICollection<Accesorio> Accesorios { get; set; }
        public virtual ICollection<Cuba> Cubas { get; set; }
        public virtual ICollection<Compartimento> Compartimentos { get; set; }
    }
}
