//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operacion
    {
        public int id { get; set; }
        public Nullable<int> cuba_id { get; set; }
        public Nullable<int> operacion_id { get; set; }
        public Nullable<System.DateTime> fecha_operacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> operario_id { get; set; }
        public Nullable<System.TimeSpan> duracion { get; set; }
    
        public virtual cuba cuba { get; set; }
        public virtual operario operario { get; set; }
        public virtual tipo_operacion tipo_operacion { get; set; }
    }
}
