//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonasEntidad
    {
        public int ID { get; set; }
        public int EntidadID { get; set; }
        public int PersonaID { get; set; }
        public Nullable<int> CargoID { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Entidad Entidad { get; set; }
    }
}
