//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanMantenimiento
    {
        public int PlanId { get; set; }
        public Nullable<int> AccesorioId { get; set; }
        public int PeriodicidadDias { get; set; }
        public Nullable<System.DateTime> UltimaEjecucion { get; set; }
        public Nullable<System.DateTime> ProximaEjecucion { get; set; }
        public Nullable<int> AccesorioGrupoID { get; set; }
        public Nullable<int> EquipoId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> FrecuenciaValor { get; set; }
        public string FrecuenciaUnidad { get; set; }
        public Nullable<int> DuracionEstimadaMinutos { get; set; }
        public bool Activo { get; set; }
    
        public virtual Accesorio Accesorio { get; set; }
        public virtual AccesorioGrupo AccesorioGrupo { get; set; }
    }
}
