//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanMantenimiento
    {
        public int PlanId { get; set; }
        public int AccesorioId { get; set; }
        public int PeriodicidadDias { get; set; }
        public Nullable<System.DateTime> UltimaEjecucion { get; set; }
        public Nullable<System.DateTime> ProximaEjecucion { get; set; }
    
        public virtual Accesorio Accesorio { get; set; }
    }
}
