//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Plataforma
    {
        public Plataforma()
        {
            this.Cuba = new HashSet<Cuba>();
        }
    
        public int ID { get; set; }

        [Display(Name = "Matrícula Plataforma")]
        public string MatriculaPlataforma { get; set; }
        public string Propiedad { get; set; }

        [Display(Name = "P.M.A.")]
        public Nullable<int> Pma { get; set; }
    
        public virtual ICollection<Cuba> Cuba { get; set; }
    }
}
