//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Compartimentos = new HashSet<Compartimento>();
        }
    
        public int ID { get; set; }
        public string Iupac { get; set; }
        public string Producto1 { get; set; }
        public Nullable<int> Concentracion { get; set; }
        public Nullable<int> Grupo { get; set; }
        public string NumUN { get; set; }
        public string Formula { get; set; }
        public Nullable<int> Densidad { get; set; }
        public string FrasesR { get; set; }
        public string FrasesS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compartimento> Compartimentos { get; set; }
    }
}
