//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.compartimentoes = new HashSet<compartimento>();
        }
    
        public int id { get; set; }
        public string iupac { get; set; }
        public string producto1 { get; set; }
        public Nullable<int> concentracion { get; set; }
        public Nullable<int> grupo { get; set; }
        public string num_UN { get; set; }
        public string formula { get; set; }
        public Nullable<int> densidad { get; set; }
        public string frases_R { get; set; }
        public string frases_S { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compartimento> compartimentoes { get; set; }
    }
}
