//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RevisionVehiculo
    {
        public int ID { get; set; }
        public Nullable<int> VehiculoID { get; set; }
        public Nullable<int> TipoRevisionID { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public string Detalles { get; set; }
        public string Ejecutor { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Caducidad { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
        public virtual TipoRevision TipoRevision { get; set; }
    }
}
