//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        public int ID { get; set; }
        public Nullable<int> CubaID { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> ValidaHasta { get; set; }
        public string DescripcionProxima { get; set; }
        public string Autorizado { get; set; }
    }
}
