//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Situacion
    {
        public int ID { get; set; }
        public Nullable<int> LadoCubaNumero { get; set; }
        public string LadoCubaNombre { get; set; }
        public Nullable<int> SituacionLadoNumero { get; set; }
        public string SituacionLadoLetra { get; set; }
    }
}
