//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de GaillardModel.edmx.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CasaGaillard.Models
{
    using System;

    public partial class TipoInstalacion
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}
