//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string username { get; set; }
        public string auth_key { get; set; }
        public string password_hash { get; set; }
        public string password_reset_token { get; set; }
        public string email { get; set; }
        public short status { get; set; }
        public short rol_id { get; set; }
        public int created_at { get; set; }
        public short updated_at { get; set; }
    }
}
