//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int ID { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string MatriculaVehiculo { get; set; }
        public Nullable<int> TipoVehiculoID { get; set; }
        public string ModeloTacografo { get; set; }
        public Nullable<int> Pma { get; set; }
        public Nullable<int> Tara { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public string TallerHabitual { get; set; }
    }
}
