//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaGaillard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.RevisionesVehiculo = new HashSet<RevisionVehiculo>();
            this.MantenimientosVehiculo = new HashSet<MantenimientoVehiculo>();
            this.Cubas = new HashSet<Cuba>();
        }
    
        public int ID { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string MatriculaVehiculo { get; set; }
        public int TipoVehiculoID { get; set; }
        public string ModeloTacografo { get; set; }
        public Nullable<int> Pma { get; set; }
        public Nullable<int> Tara { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<int> CargaUtil { get; set; }
        public Nullable<int> KilometrajeCompra { get; set; }
        public Nullable<int> TallerHabitualID { get; set; }
        public string NumBastidor { get; set; }
        public Nullable<int> TipoCombustible { get; set; }
        public Nullable<int> NumEjes { get; set; }
        public Nullable<int> PotenciaCV { get; set; }
        public Nullable<int> Longitud { get; set; }
        public Nullable<int> Anchura { get; set; }
        public Nullable<int> Altura { get; set; }
        public Nullable<int> SeguroID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevisionVehiculo> RevisionesVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoVehiculo> MantenimientosVehiculo { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
        public virtual Entidad Taller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuba> Cubas { get; set; }
        public virtual Vehiculo Vehiculo1 { get; set; }
        public virtual Vehiculo Vehiculo2 { get; set; }
    }
}
